<?php

namespace App\Http\Controllers\Voyager;

use TCG\Voyager\Http\Controllers\VoyagerController as BaseVoyagerController;

class VoyagerController extends BaseVoyagerController
{
    //
    public function index()
    {
        return view('voyager.index');
//        return parent::index(); // TODO: Change the autogenerated stub
    }
}
